/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users */
        get: operations["read_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User */
        get: operations["read_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/active-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Active Plan
         * @description Der aktive Plan samt Trainingstagen - das laedt das Hauptmenue.
         */
        get: operations["read_active_plan_api_v1_users__user_id__active_plan_get"];
        /**
         * Set Active Plan
         * @description Waehlt den aktiven Trainingsplan. workout_plan_id=null hebt die Wahl auf.
         *
         *     PUT statt PATCH: es gibt genau einen aktiven Plan, der Aufruf setzt ihn
         *     vollstaendig - zweimal derselbe Aufruf hat dasselbe Ergebnis.
         */
        put: operations["set_active_plan_api_v1_users__user_id__active_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/log/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Log
         * @description Ansicht 1: die Historie, neueste zuerst.
         *
         *     Freie Trainings stehen mit drin und tragen den Typ "Custom" - nur aus
         *     der Auswertung bleiben sie heraus.
         */
        get: operations["read_log_api_v1_users__user_id__log_workouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/log/months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Months
         * @description Die Monate mit Einheiten, neueste zuerst - fuer die beiden Dropdowns.
         */
        get: operations["read_months_api_v1_users__user_id__log_months_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/log/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Progress
         * @description Ansicht 2: Fortschritt je Uebung, Monat A gegen Monat B.
         *
         *     Beide Monate waehlt der User frei - auch weit auseinanderliegende, wie
         *     09/25 gegen 04/26. Genau dafuer haengen die Uebungen am User und nicht
         *     am Plan: sonst waeren es ueber einen Planwechsel hinweg zwei
         *     verschiedene Uebungen und es gaebe nichts zu vergleichen.
         */
        get: operations["read_progress_api_v1_users__user_id__log_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Workout Plans */
        get: operations["read_workout_plans_api_v1_workout_plans_get"];
        put?: never;
        /**
         * Create Workout Plan
         * @description Legt einen Plan an, optional gleich mit seinen Trainingstagen.
         *
         *     Die Tage lassen sich mitschicken, weil beim Anlegen ohnehin feststeht,
         *     an wie vielen Tagen pro Woche was trainiert wird. Ein leerer Plan ist
         *     ebenfalls erlaubt - die Tage kommen dann ueber /training-days dazu.
         */
        post: operations["create_workout_plan_api_v1_workout_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Workout Plan
         * @description Plan inklusive Trainingstage, Uebungen und Vorgaben - Detailansicht der PWA.
         */
        get: operations["read_workout_plan_api_v1_workout_plans__plan_id__get"];
        put?: never;
        post?: never;
        /** Delete Workout Plan */
        delete: operations["delete_workout_plan_api_v1_workout_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /** Update Workout Plan */
        patch: operations["update_workout_plan_api_v1_workout_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/v1/training-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Training Days */
        get: operations["read_training_days_api_v1_training_days_get"];
        put?: never;
        /** Create Training Day */
        post: operations["create_training_day_api_v1_training_days_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training-days/{training_day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Training Day
         * @description Tag samt Uebungen und Vorgaben - das laedt der Workout-Screen beim Start.
         */
        get: operations["read_training_day_api_v1_training_days__training_day_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Training Day
         * @description Loescht den Tag. Bereits absolvierte Einheiten bleiben erhalten und
         *     gelten danach als freies Training (training_day_id wird NULL).
         */
        delete: operations["delete_training_day_api_v1_training_days__training_day_id__delete"];
        options?: never;
        head?: never;
        /** Update Training Day */
        patch: operations["update_training_day_api_v1_training_days__training_day_id__patch"];
        trace?: never;
    };
    "/api/v1/training-days/{training_day_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Exercise To Day
         * @description Setzt eine Katalog-Uebung mit Vorgabe ("3x8-10") auf den Trainingstag.
         */
        post: operations["add_exercise_to_day_api_v1_training_days__training_day_id__exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/training-days/{training_day_id}/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Exercise From Day
         * @description Nimmt die Uebung vom Plan. Der Katalogeintrag und die bereits
         *     protokollierten Saetze bleiben bestehen.
         */
        delete: operations["remove_exercise_from_day_api_v1_training_days__training_day_id__exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Day Exercise
         * @description Aendert die Vorgabe, z.B. von 3x8-10 auf 4x6-8.
         */
        patch: operations["update_day_exercise_api_v1_training_days__training_day_id__exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Exercises
         * @description Der Katalog eines Users, oder die Uebungen, die in einem Plan vorkommen.
         */
        get: operations["read_exercises_api_v1_exercises_get"];
        put?: never;
        /**
         * Create Exercise
         * @description Legt eine Uebung im Katalog des Users an.
         */
        post: operations["create_exercise_api_v1_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Exercise */
        get: operations["read_exercise_api_v1_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Exercise
         * @description Loescht die Uebung samt ihrer protokollierten Saetze.
         *
         *     Achtung: damit verschwindet auch der Verlauf dieser Uebung aus der
         *     Auswertung - das Frontend sollte davor warnen.
         */
        delete: operations["delete_exercise_api_v1_exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_api_v1_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/v1/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Sets
         * @description Saetze filterbar nach Uebung (Verlauf) und/oder Einheit (Tagesprotokoll).
         */
        get: operations["read_sets_api_v1_sets_get"];
        put?: never;
        /**
         * Create Set
         * @description Protokolliert einen absolvierten Satz innerhalb einer Trainingseinheit.
         */
        post: operations["create_set_api_v1_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Set */
        get: operations["read_set_api_v1_sets__set_id__get"];
        put?: never;
        post?: never;
        /** Delete Set */
        delete: operations["delete_set_api_v1_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set */
        patch: operations["update_set_api_v1_sets__set_id__patch"];
        trace?: never;
    };
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Workouts
         * @description Trainingshistorie - filterbar nach Plan oder User, optional ab einem Datum.
         */
        get: operations["read_workouts_api_v1_workouts_get"];
        put?: never;
        /**
         * Create Workout
         * @description Legt eine Einheit an.
         *
         *     Mit training_day_id wird ein geplanter Tag trainiert ("Push"), ohne sie
         *     ein freies Training - z.B. wenn im Hotel die Geraete fehlen. Freie
         *     Einheiten stehen in der Historie, zaehlen aber nicht in die Auswertung.
         */
        post: operations["create_workout_api_v1_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Workout
         * @description Detailansicht: die Einheit mit allen darin protokollierten Saetzen.
         */
        get: operations["read_workout_api_v1_workouts__workout_id__get"];
        put?: never;
        post?: never;
        /** Delete Workout */
        delete: operations["delete_workout_api_v1_workouts__workout_id__delete"];
        options?: never;
        head?: never;
        /** Update Workout */
        patch: operations["update_workout_api_v1_workouts__workout_id__patch"];
        trace?: never;
    };
    "/api/v1/workouts/{workout_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Workout
         * @description Startet die Einheit und laesst die Uhr laufen.
         *
         *     Der Zeitstempel kommt vom Server, nicht vom Client - sonst haengt die
         *     gemessene Dauer davon ab, wie richtig die Uhr des Handys geht.
         */
        post: operations["start_workout_api_v1_workouts__workout_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{workout_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish Workout
         * @description Beendet die laufende Einheit. Die Dauer ergibt sich aus der Differenz.
         */
        post: operations["finish_workout_api_v1_workouts__workout_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Einfacher Lebenszeichen-Endpunkt (praktisch fuers Deployment).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivePlanUpdate
         * @description Body fuer PUT /users/{id}/active-plan. None hebt die Auswahl auf.
         */
        ActivePlanUpdate: {
            /** Workout Plan Id */
            workout_plan_id?: number | null;
        };
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Title */
            title: string;
            /**
             * Weighted
             * @default true
             */
            weighted: boolean;
            /** User Id */
            user_id: number;
        };
        /**
         * ExerciseMonthStats
         * @description Die Zahlen einer Uebung in einem Monat.
         */
        ExerciseMonthStats: {
            /** Best Weight */
            best_weight?: string | null;
            /** Best Reps */
            best_reps?: number | null;
            /** Avg Reps */
            avg_reps?: number | null;
            /** Avg Weight */
            avg_weight?: string | null;
            /**
             * Set Count
             * @default 0
             */
            set_count: number;
            /**
             * Session Count
             * @default 0
             */
            session_count: number;
        };
        /** ExerciseProgress */
        ExerciseProgress: {
            /** Exercise Id */
            exercise_id: number;
            /** Title */
            title: string;
            /** Weighted */
            weighted: boolean;
            month_a?: components["schemas"]["ExerciseMonthStats"] | null;
            month_b?: components["schemas"]["ExerciseMonthStats"] | null;
            delta: components["schemas"]["ExerciseProgressDelta"];
        };
        /**
         * ExerciseProgressDelta
         * @description Differenz B minus A. None, wenn eine Seite fehlt.
         */
        ExerciseProgressDelta: {
            /** Best Weight */
            best_weight?: string | null;
            /** Best Reps */
            best_reps?: number | null;
            /** Avg Reps */
            avg_reps?: number | null;
            /** Avg Weight */
            avg_weight?: string | null;
        };
        /** ExercisePublic */
        ExercisePublic: {
            /** Title */
            title: string;
            /**
             * Weighted
             * @default true
             */
            weighted: boolean;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
        };
        /** ExerciseUpdate */
        ExerciseUpdate: {
            /** Title */
            title?: string | null;
            /** Weighted */
            weighted?: boolean | null;
        };
        /**
         * ExerciseWithSets
         * @description Uebung inklusive ihrer Saetze.
         */
        ExerciseWithSets: {
            /** Title */
            title: string;
            /**
             * Weighted
             * @default true
             */
            weighted: boolean;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["SetPublic"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MonthOption
         * @description Ein Monat, in dem tatsaechlich trainiert wurde.
         *
         *     Fuellt die beiden Dropdowns der Auswertung - so kann der User keinen
         *     leeren Monat waehlen.
         */
        MonthOption: {
            /**
             * Month
             * @example 2026-04
             */
            month: string;
            /**
             * Label
             * @example 04/2026
             */
            label: string;
            /** Workout Count */
            workout_count: number;
        };
        /**
         * ProgressComparison
         * @description Auswertung zweier Monate, z.B. 09/25 gegen 04/26.
         */
        ProgressComparison: {
            /** Month A */
            month_a: string;
            /** Month B */
            month_b: string;
            /** Label A */
            label_a: string;
            /** Label B */
            label_b: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseProgress"][];
            /**
             * Excluded Custom Workouts
             * @default 0
             */
            excluded_custom_workouts: number;
        };
        /** SetCreate */
        SetCreate: {
            /** Repetitions */
            repetitions: number;
            /** Weight */
            weight?: number | null;
            /** Exercise Id */
            exercise_id: number;
            /** Workout Id */
            workout_id: number;
        };
        /** SetPublic */
        SetPublic: {
            /** Repetitions */
            repetitions: number;
            /** Weight */
            weight?: number | null;
            /** Id */
            id: number;
            /** Exercise Id */
            exercise_id: number;
            /** Workout Id */
            workout_id: number;
        };
        /** SetUpdate */
        SetUpdate: {
            /** Repetitions */
            repetitions?: number | null;
            /** Weight */
            weight?: number | null;
        };
        /** TrainingDayCreate */
        TrainingDayCreate: {
            /** Position */
            position: number;
            /** Workout Type */
            workout_type: string;
            /** Workout Plan Id */
            workout_plan_id: number;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["TrainingDayExerciseCreate"][];
        };
        /**
         * TrainingDayExerciseCreate
         * @description Haengt eine Katalog-Uebung mit Vorgabe an einen Trainingstag.
         */
        TrainingDayExerciseCreate: {
            /**
             * Position
             * @default 1
             */
            position: number;
            /**
             * Target Sets
             * @default 3
             */
            target_sets: number;
            /** Target Reps Min */
            target_reps_min?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
            /** Exercise Id */
            exercise_id: number;
        };
        /** TrainingDayExercisePublic */
        TrainingDayExercisePublic: {
            /**
             * Position
             * @default 1
             */
            position: number;
            /**
             * Target Sets
             * @default 3
             */
            target_sets: number;
            /** Target Reps Min */
            target_reps_min?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
            /** Training Day Id */
            training_day_id: number;
            /** Exercise Id */
            exercise_id: number;
            exercise: components["schemas"]["ExercisePublic"];
        };
        /** TrainingDayExerciseUpdate */
        TrainingDayExerciseUpdate: {
            /** Position */
            position?: number | null;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps Min */
            target_reps_min?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
        };
        /**
         * TrainingDayNested
         * @description Trainingstag beim Anlegen eines Plans - die plan-id steht dann schon fest.
         */
        TrainingDayNested: {
            /** Position */
            position: number;
            /** Workout Type */
            workout_type: string;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["TrainingDayExerciseCreate"][];
        };
        /** TrainingDayPublic */
        TrainingDayPublic: {
            /** Position */
            position: number;
            /** Workout Type */
            workout_type: string;
            /** Id */
            id: number;
            /** Workout Plan Id */
            workout_plan_id: number;
        };
        /** TrainingDayUpdate */
        TrainingDayUpdate: {
            /** Position */
            position?: number | null;
            /** Workout Type */
            workout_type?: string | null;
        };
        /**
         * TrainingDayWithExercises
         * @description Trainingstag samt Uebungen und Vorgaben - das braucht der Workout-Screen.
         */
        TrainingDayWithExercises: {
            /** Position */
            position: number;
            /** Workout Type */
            workout_type: string;
            /** Id */
            id: number;
            /** Workout Plan Id */
            workout_plan_id: number;
            /**
             * Exercise Links
             * @default []
             */
            exercise_links: components["schemas"]["TrainingDayExercisePublic"][];
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** Weight */
            weight: number;
        };
        /** UserPublic */
        UserPublic: {
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** Weight */
            weight: number;
            /** Id */
            id: number;
            /** Active Workout Plan Id */
            active_workout_plan_id?: number | null;
        };
        /**
         * UserUpdate
         * @description Alle Felder optional - fuer PATCH, das nur einzelne Felder aendert.
         */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Age */
            age?: number | null;
            /** Weight */
            weight?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkoutCreate */
        WorkoutCreate: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /**
             * Attended
             * @default true
             */
            attended: boolean;
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Workout Plan Id */
            workout_plan_id: number;
            /** Training Day Id */
            training_day_id?: number | null;
        };
        /**
         * WorkoutLogEntry
         * @description Eine Zeile der Historie.
         */
        WorkoutLogEntry: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Attended */
            attended: boolean;
            /** Comment */
            comment: string;
            /** Workout Type */
            workout_type: string;
            /** Is Custom */
            is_custom: boolean;
            /** Plan Title */
            plan_title: string;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Duration */
            duration?: string | null;
            /** Set Count */
            set_count: number;
            /** Exercise Count */
            exercise_count: number;
        };
        /** WorkoutPlanCreate */
        WorkoutPlanCreate: {
            /** Title */
            title: string;
            /** Starting Date */
            starting_date?: string | null;
            /** Ending Date */
            ending_date?: string | null;
            /** User Id */
            user_id: number;
            /**
             * Training Days
             * @default []
             */
            training_days: components["schemas"]["TrainingDayNested"][];
        };
        /** WorkoutPlanPublic */
        WorkoutPlanPublic: {
            /** Title */
            title: string;
            /** Starting Date */
            starting_date?: string | null;
            /** Ending Date */
            ending_date?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
        };
        /** WorkoutPlanUpdate */
        WorkoutPlanUpdate: {
            /** Title */
            title?: string | null;
            /** Starting Date */
            starting_date?: string | null;
            /** Ending Date */
            ending_date?: string | null;
        };
        /**
         * WorkoutPlanWithDays
         * @description Plan inklusive Trainingstage und deren Uebungen - Detailansicht der PWA.
         */
        WorkoutPlanWithDays: {
            /** Title */
            title: string;
            /** Starting Date */
            starting_date?: string | null;
            /** Ending Date */
            ending_date?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Training Days
             * @default []
             */
            training_days: components["schemas"]["TrainingDayWithExercises"][];
            /**
             * Training Days Per Week
             * @description Abgeleitet aus der Anzahl der Tage, nicht separat gespeichert.
             */
            readonly training_days_per_week: number;
        };
        /** WorkoutPublic */
        WorkoutPublic: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /**
             * Attended
             * @default true
             */
            attended: boolean;
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: number;
            /** Workout Plan Id */
            workout_plan_id: number;
            /** Training Day Id */
            training_day_id?: number | null;
            /**
             * Is Custom
             * @description Freies Training - erscheint in der Historie, nicht in der Auswertung.
             */
            readonly is_custom: boolean;
            /**
             * Duration Seconds
             * @description Abgeleitet, nicht gespeichert - None solange die Einheit laeuft.
             */
            readonly duration_seconds: number | null;
            /**
             * Duration
             * @description Dauer als "01:43:32" - fertig zum Anzeigen, ohne Rechnerei im Frontend.
             */
            readonly duration: string | null;
            /**
             * Is Running
             * @description True zwischen /start und /finish - das Frontend zeigt dann die
             *     laufende Uhr statt der Enddauer.
             */
            readonly is_running: boolean;
        };
        /**
         * WorkoutUpdate
         * @description Alle Felder optional - die Pruefung der Zeitlogik passiert im Router,
         *     weil dort erst feststeht, wie der Datensatz nach dem PATCH aussieht.
         */
        WorkoutUpdate: {
            /** Date */
            date?: string | null;
            /** Attended */
            attended?: boolean | null;
            /** Comment */
            comment?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Training Day Id */
            training_day_id?: number | null;
        };
        /**
         * WorkoutWithSets
         * @description Einheit inklusive der Saetze, die darin absolviert wurden.
         */
        WorkoutWithSets: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /**
             * Attended
             * @default true
             */
            attended: boolean;
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: number;
            /** Workout Plan Id */
            workout_plan_id: number;
            /** Training Day Id */
            training_day_id?: number | null;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["SetPublic"][];
            /**
             * Is Custom
             * @description Freies Training - erscheint in der Historie, nicht in der Auswertung.
             */
            readonly is_custom: boolean;
            /**
             * Duration Seconds
             * @description Abgeleitet, nicht gespeichert - None solange die Einheit laeuft.
             */
            readonly duration_seconds: number | null;
            /**
             * Duration
             * @description Dauer als "01:43:32" - fertig zum Anzeigen, ohne Rechnerei im Frontend.
             */
            readonly duration: string | null;
            /**
             * Is Running
             * @description True zwischen /start und /finish - das Frontend zeigt dann die
             *     laufende Uhr statt der Enddauer.
             */
            readonly is_running: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_users_api_v1_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_active_plan_api_v1_users__user_id__active_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanWithDays"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_active_plan_api_v1_users__user_id__active_plan_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivePlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_log_api_v1_users__user_id__log_workouts_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_months_api_v1_users__user_id__log_months_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_progress_api_v1_users__user_id__log_progress_get: {
        parameters: {
            query: {
                /** @description Monat im Format JJJJ-MM */
                month_a: string;
                /** @description Monat im Format JJJJ-MM */
                month_b: string;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_workout_plans_api_v1_workout_plans_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_plan_api_v1_workout_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_workout_plan_api_v1_workout_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanWithDays"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_plan_api_v1_workout_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_plan_api_v1_workout_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutPlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_training_days_api_v1_training_days_get: {
        parameters: {
            query?: {
                workout_plan_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDayPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_training_day_api_v1_training_days_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingDayCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDayPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_training_day_api_v1_training_days__training_day_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_day_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDayWithExercises"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_training_day_api_v1_training_days__training_day_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_day_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_training_day_api_v1_training_days__training_day_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_day_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingDayUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDayPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_exercise_to_day_api_v1_training_days__training_day_id__exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_day_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingDayExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDayExercisePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_exercise_from_day_api_v1_training_days__training_day_id__exercises__exercise_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_day_id: number;
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_day_exercise_api_v1_training_days__training_day_id__exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_day_id: number;
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingDayExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDayExercisePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_exercises_api_v1_exercises_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                workout_plan_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_v1_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_exercise_api_v1_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithSets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exercise_api_v1_exercises__exercise_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_api_v1_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_sets_api_v1_sets_get: {
        parameters: {
            query?: {
                exercise_id?: number | null;
                workout_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_set_api_v1_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_set_api_v1_sets__set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_api_v1_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_api_v1_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_workouts_api_v1_workouts_get: {
        parameters: {
            query?: {
                workout_plan_id?: number | null;
                user_id?: number | null;
                since?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_api_v1_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_workout_api_v1_workouts__workout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutWithSets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_api_v1_workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_api_v1_workouts__workout_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workout_api_v1_workouts__workout_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_workout_api_v1_workouts__workout_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
