"""workout start und ende

Ergaenzt workout um started_at und finished_at, damit sich die Dauer einer
Einheit ergibt. Beide Spalten sind nullable - eine Einheit kann noch nicht
begonnen (beide NULL), gerade laufend (nur started_at) oder abgeschlossen
(beide gesetzt) sein. Bestandszeilen bleiben deshalb ohne Backfill gueltig:
fuer sie ist die Dauer schlicht unbekannt.

Die Dauer selbst wird bewusst nicht gespeichert, sondern berechnet - eine
gespeicherte Dauer koennte von den Zeitstempeln abweichen. Die beiden
CHECK-Constraints halten die Regeln auch dann ein, wenn jemand an der API
vorbei direkt in die DB schreibt.

Revision ID: 418fec70b608
Revises: be2744409682
Create Date: 2026-09-01 12:34:01.663140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418fec70b608'
down_revision: Union[str, Sequence[str], None] = 'be2744409682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint('workout_ende_nach_start', 'workout', 'finished_at IS NULL OR finished_at >= started_at')
    op.create_check_constraint('workout_finish_braucht_start', 'workout', 'finished_at IS NULL OR started_at IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_finish_braucht_start', 'workout', type_='check')
    op.drop_constraint('workout_ende_nach_start', 'workout', type_='check')
    op.drop_column('workout', 'finished_at')
    op.drop_column('workout', 'started_at')
    # ### end Alembic commands ###
