"""initial schema

Revision ID: 88d6bbc62c6c
Revises: 
Create Date: 2026-09-05 18:52:11.869196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d6bbc62c6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active_workout_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_workout_plan_id'], ['workout_plan.id'], name='fk_appuser_active_workout_plan', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('weighted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['appuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', name='exercise_titel_je_user_einmalig')
    )
    op.create_table('workout_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=True),
    sa.Column('ending_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['appuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_plan_id', 'position', name='training_day_position_einmalig')
    )
    op.create_table('training_day_exercise',
    sa.Column('training_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.CheckConstraint('target_reps_max IS NULL OR target_reps_min IS NULL OR target_reps_max >= target_reps_min', name='rep_range_richtig_herum'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_day_id', 'exercise_id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('body_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name='workout_ende_nach_start'),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NOT NULL', name='workout_finish_braucht_start'),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_day.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid', name='workout_client_uuid_einmalig')
    )
    op.create_index(op.f('ix_workout_training_day_id'), 'workout', ['training_day_id'], unique=False)
    op.create_table('exercise_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_set_workout_id'), 'exercise_set', ['workout_id'], unique=False)
    # Zirkulaerer Fremdschluessel: appuser.active_workout_plan_id zeigt auf
    # workout_plan.id, waehrend workout_plan.user_id auf appuser.id zeigt. In
    # der Tabellendefinition oben steht er mit use_alter=True - dort wird er
    # deshalb NICHT mit erzeugt, weil er beide Tabellen braucht. Autogenerate
    # laesst ihn stillschweigend weg, also hier von Hand per ALTER TABLE,
    # genau wie es Base.metadata.create_all() auch tut.
    op.create_foreign_key(
        'fk_appuser_active_workout_plan',
        'appuser',
        'workout_plan',
        ['active_workout_plan_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Zuerst den nachtraeglich ergaenzten Fremdschluessel loesen, sonst
    # blockiert er das Loeschen der Tabellen.
    op.drop_constraint('fk_appuser_active_workout_plan', 'appuser', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_set_workout_id'), table_name='exercise_set')
    op.drop_table('exercise_set')
    op.drop_index(op.f('ix_workout_training_day_id'), table_name='workout')
    op.drop_table('workout')
    op.drop_table('training_day_exercise')
    op.drop_table('training_day')
    op.drop_table('workout_plan')
    op.drop_table('exercise')
    op.drop_table('appuser')
    # ### end Alembic commands ###
